export const softSkills = [
    'Teamwork',
    'Critical Thinking',
    'Problem solving',
    'Time management',
    'Good communication',
    'Fast learning'
]

export const hardSkills = [
    'JavaScript',
    'TypeScript',
    'PHP',
    'Basics of Java',
    'React.js',
    'React Query',
    'Next.js',
    'Laravel',
    'Domain-Driven Architecture',
    'Authentication',
    'API Integration',
    'Inertia.js',
    'WordPress',
    'Bedrock',
    'Acorn',
    'Sage',
    'Docker',
    'Nginx',
    'SEO',
    'SSR (Server-Side Rendering)',
    'Performance Optimization',
    'MySQL',
    'HTML',
    'CSS',
    'SASS',
    'Tailwind',
    'Redux Toolkit',
    'Axios',
    'REST Api',
    'Moonshine',
    'Spatie',
    'Lodash',
    'Swiper',
    'Toastify',
    'Tawk API',
    'Material UI',
    'Git',
    'BEM',
    'ESLint',
    'Husky',
    'Prettier',
    'Postman',
    'Slack',
    'Figma'
]
