export const softSkills = [
    'Teamwork',
    'Critical Thinking',
    'Problem solving',
    'Time management',
    'Good communication',
    'Fast learning'
]

export const hardSkills = [
    'JavaScript',
    'TypeScript',
    'React.js',
    'React Query',
    'Next.js',
    'PHP',
    'Laravel',
    'Domain-Driven Architecture',
    'Authentication',
    'API Integration',
    'Inertia.js',
    'WordPress',
    'Bedrock',
    'Acorn',
    'Sage',
    'Basics of Java',
    'Docker',
    'Nginx',
    'SEO',
    'SSR (Server-Side Rendering)',
    'Performance Optimization',
    'MySQL',
    'HTML',
    'CSS',
    'SASS',
    'Tailwind',
    'Redux Toolkit',
    'Axios',
    'REST Api',
    'Moonshine',
    'Spatie',
    'Lodash',
    'Swiper',
    'Toastify',
    'Tawk API',
    'Material UI',
    'Git',
    'BEM',
    'ESLint',
    'Husky',
    'Prettier',
    'Postman',
    'Slack',
    'Figma'
]
